# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25893c91229939ce8cb7a33dd50a75b7ea0252a401d690b7244c6e3e5ffcc7e6b60d24b367892d2465bf10ac2b9b260e7aa5efde8ed9bfe13aee97d15ea07a45

test:
  secret_key_base: e3398d4b87accabfa1b88048292a00d8856930bc8c20fa5d4362723082211df2b3fd73ef52ebff488bf123cb9b95574fee74780959595bd5cdd9a8d1397c70f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
